### ISSUE TITLE
Keyring error on headless server

### ISSUE THREAD

**Issue by majal** [certikfoundation/chain#10]
Hi!

There is no problem running `certikcli keys add test` on a Ubuntu machine with GUI. I've now tested on two cloud providers (Google and Hetzner) on a headless server. Both have issues with the keyring. Running the same command as before throws this error:

```
panic: No such interface “org.freedesktop.DBus.Properties” on object at path /

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeInfo(0x155ed88, 0x155ed80, 0xc000fd9e10, 0x1, 0x1, 0xc000fd9e20, 0x1, 0x1, 0x172c000, 0xc001006750, ...)
	/mnt/c/certik-chain/vendor/github.com/cosmos/cosmos-sdk/crypto/keys/keyring.go:478 +0x38c
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeLocalKey(0x155ed88, 0x155ed80, 0xc000fd9e10, 0x1, 0x1, 0xc000fd9e20, 0x1, 0x1, 0x172c000, 0xc001006750, ...)
	/mnt/c/certik-chain/vendor/github.com/cosmos/cosmos-sdk/crypto/keys/keyring.go:464 +0x189
github.com/cosmos/cosmos-sdk/crypto/keys.baseKeybase.CreateAccount(0x155ed88, 0x155ed80, 0xc000fd9e10, 0x1, 0x1, 0xc000fd9e20, 0x1, 0x1, 0x17174e0, 0xc00054d810, ...)
	/mnt/c/certik-chain/vendor/github.com/cosmos/cosmos-sdk/crypto/keys/keybase_base.go:171 +0x192
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.CreateAccount(...)
	/mnt/c/certik-chain/vendor/github.com/cosmos/cosmos-sdk/crypto/keys/keyring.go:106
github.com/cosmos/cosmos-sdk/client/keys.RunAddCmd(0xc001000b00, 0xc000fd9550, 0x1, 0x1, 0x1741fa0, 0xc00054d7c0, 0xc000fc8f60, 0xc000f7bc48, 0x5e6707)
	/mnt/c/certik-chain/vendor/github.com/cosmos/cosmos-sdk/client/keys/add.go:273 +0x732
github.com/cosmos/cosmos-sdk/client/keys.runAddCmd(0xc001000b00, 0xc000fd9550, 0x1, 0x1, 0x0, 0x0)
	/mnt/c/certik-chain/vendor/github.com/cosmos/cosmos-sdk/client/keys/add.go:99 +0x166
github.com/spf13/cobra.(*Command).execute(0xc001000b00, 0xc000fd9530, 0x1, 0x1, 0xc001000b00, 0xc000fd9530)
	/mnt/c/certik-chain/vendor/github.com/spf13/cobra/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc000ea3600, 0x8ad350, 0xc000ea3600, 0x12cdbd5)
	/mnt/c/certik-chain/vendor/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/mnt/c/certik-chain/vendor/github.com/spf13/cobra/command.go:887
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000ea3600, 0x1561920, 0x2, 0xc000f147c0)
	/mnt/c/certik-chain/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x3c
main.main()
	/mnt/c/certik-chain/cmd/certikcli/main.go:80 +0x5cc
```

I'm not sure if the problem is because headless servers don't have GUI? What can we do about this? Thanks!

**Comment by yoongbok-lee** [comment]
By default the certikcli will try to register the key as `os` as the backend. I don't know exactly what goes wrong, but you can switch the keyring-backend to 'file' or 'test' with command `certikcli config keyring-backend <type>`

**Comment by majal** [comment]
Thanks for the tip. I was only able to fix this by completely removing the folder `~/.certikd/config` which is tantamount to wiping the validator. I also realized that `certikcli config keyring-backend test` will prevent asking for a keyring passphrase, which is useful for automating tasks via scripting.
